### ISSUE TITLE
node don't want to sync on MacOS Catalina (node v1.2.6.7)

### ISSUE THREAD

**Issue by realForbis** [qlcchain/QLCTracker#28]
<img width="1372" alt="Snímek obrazovky 2019-11-09 v 7 17 29" src="https://user-images.githubusercontent.com/37193612/68524022-64203f00-02c1-11ea-953a-dadc0ea9a53f.png">
<img width="1372" alt="Snímek obrazovky 2019-11-09 v 7 13 56 1" src="https://user-images.githubusercontent.com/37193612/68524023-64203f00-02c1-11ea-9923-a1557ea02911.png">

**Comment by ariesunny** [comment]
Hi, how's the sync going on? I tried on my Mac with node V1.2.6.7, it takes about 10 minutes to finish sync😂

**Comment by ariesunny** [comment]
Hi realForbis, Please try the latest V1.3.0 version, any issues please let us know, Thanks.
