### ISSUE TITLE
Error when using public node rpc on version 1.4.1

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/QLCTracker#55]
![image](https://user-images.githubusercontent.com/30827440/105271193-0af4b080-5bd2-11eb-9754-5fff7206dde5.png)

**Comment by beichenzhidi** [comment]
win10 家庭版发现的两个问题：
1.初始化时弹窗偶尔不能弹出

![image](https://user-images.githubusercontent.com/17975699/105654851-d77b9400-5ef9-11eb-8d60-4217d52f21b4.png)

![image](https://user-images.githubusercontent.com/17975699/105654875-e5c9b000-5ef9-11eb-81ab-4419d27a98d2.png)
![image](https://user-images.githubusercontent.com/17975699/105654794-b4e97b00-5ef9-11eb-8d7f-9cd9ba8db050.png)
2.创建neo wallet失败

![image](https://user-images.githubusercontent.com/17975699/105654737-96837f80-5ef9-11eb-82bf-90c92b222e63.png)

**Comment by beichenzhidi** [comment]
桌面版正反向交易已完成，收不到Hub确认信息，页面不跳转
![image](https://user-images.githubusercontent.com/17975699/105930201-2ce3ac80-6084-11eb-9391-ffbd44fd985a.png)

**Comment by beichenzhidi** [comment]
fixed
