### ISSUE TITLE
Metamask not popping up with action when swaping ERC-20 -> NEP5

### ISSUE THREAD

**Issue by realForbis** [qlcchain/QLCTracker#63]

**Comment by beichenzhidi** [comment]
Please make sure whether you are connected to the metamask wallet and whether the account balance of the current transaction is sufficient to pay the gas fee. If these prerequisites are met, it is best to provide a screenshot. We will then specifically locate the problem, and we will do our best to ensure that you swap happy

**Comment by realForbis** [comment]
it wasn't my problem I was only forwarding it but it seems to be working again, so I'm closing it for now
