### ISSUE TITLE
Bug - Not able to import Neo Wallet using PK/ Generate new Neo Wallet in Chrome

### ISSUE THREAD

**Issue by RealBluePhoenix** [qlcchain/QLCTracker#89]
i'm not able to create new neo wallet and not able to import neo PK in QLC Tracker...
 Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by beichenzhidi** [comment]
Hello, we found that the service is normal after investigation. The functions of creating a new neo wallet and importing neo wallet are all normal. Please try again. If you still have problems, please provide a screenshot so that we can continue to help you locate the problem, thank you

**Comment by RealBluePhoenix** [comment]
Yes, after today's update of the code, the issue is fixed. 
Thanks.
I will close the issue...
